### ISSUE TITLE
How to make it work in API's

### ISSUE THREAD

**Issue by Xoshbin** [cyrildewit/eloquent-viewable#82]
- Eloquent Viewable: latest
- Laravel Version: 5.6
- PHP Version: 7.0
- Database Driver & Version:MySQL

### Description:
I have an API that returns a post and I want to implement the eloquent-viewable package but it seems it's not working on the API side whatever I do even when I try to return the API from browser, anyway when I'm testing it on browser on a web routes it's working great but the same web route when hit from postman doesn't count anything, I have disabled cache in the config file too.
### Steps To Reproduce:

1. [First Step]
make API roue from routes->api.php page in laravel that routes to the postcontroller.php->show method.
2. [Second Step]
hit that route from browser and postman bothe not working
3. [and so on...]

#### Expected behavior:

[What you expected to happen]

#### Actual behavior:

[What actually happened]

**Comment by cyrildewit** [comment]
Strange. I tested it locally and it works properly. Do you get any errors?

**Comment by Xoshbin** [comment]
No errors, Just returning the post without incrementing the view on the views table. and that's my code:
```
public function show($id)
    {
        //Show a post in json through API
        //Get a single post
        $post = Post::findOrFail($id);

        $post->addView();

        //Return a single post as resource
        return new PostResource($post);
    }
```

**Comment by cyrildewit** [comment]
Does the view get stored after hitting the API route?

**Comment by Xoshbin** [comment]
No, it's no stored.

**Comment by Mohammad-Alavi** [comment]
I have the same problem 🤔 any news on this one? 🤔 i had to change back to using v1 for now. Still waiting for the fix. Any news on this? 🤔

**Comment by zymawy** [comment]
Indeed I Thought This Is Working On v2 As v1 But I Realize That It Not Hopefully There Is Some Progress 💯

**Comment by MohamedElidrissi** [comment]
Hello, I did get the views to get saved in the views table properly with the API after I changed the visitor column's type to text because the token was too long.

**Comment by cyrildewit** [comment]
_Sorry for the delay. I'm pretty busy with school, jobs and sport right now._

Hey @Xoshbin, @Mohammad-Alavi , @zymawy and @MohamedElidrissi,

As @MohamedElidrissi already pointed out. Changing the type of the `visitor` column from `string` to `text` will fix this issue probably.

Can one of you confirm this fix?

**Comment by cyrildewit** [comment]
I released `v2.4.3` with an updated views table stub.

**Comment by Xoshbin** [comment]
It's still not working for me!
The question is how does it determine the visitor column from API routes?
Let's say from web routes if it stores the IP address of the device or some token from session, what is going to store in the visitor column if it's from API routes? because I can pass and IP address if needed!

**Comment by MohamedElidrissi** [comment]
@Xoshbin I think that only happens in localhost, when I tried before it would show a long token

**Comment by Xoshbin** [comment]
No I'm using it right now in production, every count is 127.0.0.1

**Comment by MohamedElidrissi** [comment]
@Xoshbin but if your ip is 127.0.0.1 that means you're on the same network as the server?

**Comment by Xoshbin** [comment]
That's right, Because from API routes I don't send the IP address to this library so it doesn't know what's the IP address, so it adds 127.0.0.1. That's very logic, Think about it there is no way for this library to know the IP address of my Android application that's installed on somebody's device if I'm not sending the IP address to this library!

**Comment by Xoshbin** [comment]
@MohamedElidrissi I think you have tested it from browser, It's working if you open the post from browser and it saves a token. but test it from Postman and not from routes/web.php test it from routes/api.php please.

**Comment by cyrildewit** [comment]
@Xoshbin I can finally reproduce your issue. It works properly when commenting out the following if-statement inside the addViewTo method in `ViewableService`:

```php
// If ignore bots is true and the current viewer is a bot, return false
if ($ignoreBots && $this->crawlerDetector->isBot()) {
    return false;
}
```

**Comment by cyrildewit** [comment]
Workaround would be allowing bots in development mode.

**Comment by cyrildewit** [comment]
Please let me know if this was the solution!

**Comment by cyrildewit** [comment]
What does`Request::ip();` return on a test api route?

**Comment by cyrildewit** [comment]
Also, I removed the IP address as fallback for the visitor cookie in v3.

**Comment by cyrildewit** [comment]
You can bind your own implementation of the IpAddress class to the container.

```php
// App\Providers\AppServiceProvider.php
use CyrildeWit\EloquentViewabe\Support\IpAddress;
use App\Resolvers\IpAddressResolver;

$this->app->bind(IpAddress::class, IpAddressResolver::class);
```

```php
// App\Resolvers\IpAddressResolver.php
class IpAddressResolver
{
    public function get()
    {
        return \Request::ip();
    }
}
```

**Comment by Xoshbin** [comment]
I have added a pull request, that's the only way worked for me and I think it's the only way to make it work with API's. I hope would be a helpful PR #119

**Comment by Xoshbin** [comment]
[supplying your own visitors IP address](https://github.com/cyrildewit/eloquent-viewable#supplying-your-own-visitors-ip-address)
Finally you understood me. Thanks mate.
